[package]
name = "persistence_windows"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = { path = "../data_types" }
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
iox_time = { path = "../iox_time" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
