[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1.1"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
flate2 = "1.0"
futures = "0.3.21"
generated_types = { path = "../generated_types" }
hashbrown = "0.12"
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
service_grpc_catalog = { path = "../service_grpc_catalog"}
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
object_store = "0.1.0"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
predicate = { path = "../predicate" }
schema = { version = "0.1.0", path = "../schema" }
serde = "1.0"
serde_urlencoded = "0.7"
service_grpc_schema = { path = "../service_grpc_schema" }
service_grpc_object_store = { path = "../service_grpc_object_store" }
siphasher = "0.3"
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.7"
trace = { path = "../trace/" }
workspace-hack = { path = "../workspace-hack"}
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }

[dev-dependencies]
assert_matches = "1.5"
criterion = { version = "0.3.4", features = ["async_tokio", "html_reports"] }
lazy_static = "1.4.0"
paste = "1.0.7"
pretty_assertions = "1.2.1"
rand = "0.8.3"
schema = { path = "../schema" }
test_helpers = { version = "0.1.0", path = "../test_helpers", features = ["future_timeout"] }
tokio-stream = { version = "0.1.8", default_features = false, features = [] }

[[bench]]
name = "sharder"
harness = false

[[bench]]
name = "schema_validator"
harness = false

[[bench]]
name = "e2e"
harness = false
