[package]
name = "server"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
bytes = "1.0"
chrono = { version = "0.4", default-features = false }
crc32fast = "1.3.2"
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown = "0.12"
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
internal_types = { path = "../internal_types" }
iox_object_store = { path = "../iox_object_store" }
job_registry = { path = "../job_registry" }
lifecycle = { path = "../lifecycle" }
metric = { path = "../metric" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
num_cpus = "1.13.0"
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_catalog = { path = "../parquet_catalog" }
persistence_windows = { path = "../persistence_windows" }
query = { path = "../query" }
rand = "0.8.3"
service_common = { path = "../service_common" }
snafu = "0.7"
iox_time = { path = "../iox_time" }
trace = { path = "../trace" }
tokio = { version = "1.18", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.1" }
tracker = { path = "../tracker" }
uuid = { version = "0.8", features = ["v4"] }
write_buffer = { path = "../write_buffer" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
dml = { path = "../dml" }
futures-util = { version = "0.3" }
regex = "1"
router = { path = "../router" }
test_helpers = { path = "../test_helpers" }
