[package]
name = "read_buffer"
version = "0.1.0"
authors = ["Edd Robinson <me@edd.io>"]
edition = "2021"

# Note this crate is designed to be standalone, and should not depend
# on the IOx Query Engine. The rationale is:
#
# 1. Keep the API clean (and concerns separated) and allow for potential future reuse outside of IOx
# 2. Keep change/compile/link time down during development when working on just this crate

[dependencies] # In alphabetical order
arrow = { version = "13", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
croaring = "0.6"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
either = "1.6.1"
hashbrown = "0.12"
itertools = "0.10.1"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
permutation = "0.4.0"
snafu = "0.7"
schema = { path = "../schema" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
criterion = "0.3.3"
proptest = "1.0.0"
rand = "0.8.3"
rand_distr = "0.4.2"
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "database"
harness = false

[[bench]]
name = "sum_fixed"
harness = false

[[bench]]
name = "string"
harness = false

[[bench]]
name = "read"
harness = false
