[package]
name = "lifecycle"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"
description = "Implements the IOx data lifecycle"

[dependencies]
data_types = { path = "../data_types" }
futures = "0.3"
hashbrown = "0.12"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
iox_time = { path = "../iox_time" }
tokio = { version = "1.18", features = ["macros", "parking_lot", "time"] }
tracker = { path = "../tracker" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tokio = { version = "1.18", features = ["macros", "parking_lot", "rt", "time"] }
