[package]
name = "clap_blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive", "env"] }
futures = "0.3"
humantime = "2.1.0"
iox_catalog = { path = "../iox_catalog" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
object_store = "0.1.0"
observability_deps = { path = "../observability_deps" }
snafu = "0.7"
tempfile = "3.1.0"
trace = { path = "../trace" }
trace_exporters = { path = "../trace_exporters" }
trogging = { path = "../trogging", default-features = false, features = ["clap"] }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack" }
write_buffer = { path = "../write_buffer" }

[features]
azure = ["object_store/azure"] # Optional Azure Object store support
gcp = ["object_store/gcp"] # Optional GCP object store support
aws = ["object_store/aws"] # Optional AWS / S3 object store support
