[package]
name = "service_grpc_flight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util" }
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
iox_query = { path = "../iox_query" }
service_common = { path = "../service_common" }

# Crates.io dependencies, in alphabetical order
arrow = { version = "14.0.0", features = ["prettyprint"] }
arrow-flight = "14.0.0"
bytes = "1.0"
futures = "0.3"
pin-project = "1.0"
prost = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
snafu = "0.7"
tokio = { version = "1.18", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = "0.7"
workspace-hack = { path = "../workspace-hack"}
